Task 1 part 2 implement design elements using html css
ashrafabuodeh/assignments pull request #2
Opened 2021-03-21 13:45 UTC by ashrafabuodeh

2021-03-21 15:01 UTC, araraltawarah98 commented on task_1/style.css
> +.img-profile{
Set same value in height and width

2021-03-21 15:01 UTC, araraltawarah98 commented on task_1/style.css
> +
please remove space

2021-03-21 15:01 UTC, araraltawarah98 commented on task_1/index.js
> +
remove spaces

2021-03-21 15:01 UTC, araraltawarah98 commented on task_1/index.html
> +                    <img src="assets/Double espresso-1.png" alt="Double espresso" srcset="">
please remove any unnecessary attributes

2021-03-21 15:06 UTC, abood454 requested changes
the space between elements has to be redone and redesign some parts

2021-03-21 15:06 UTC, abood454 commented on task_1/fonts/google-sans-cufonfonts-webfont/example.html
> +</html>
add one space

2021-03-21 15:06 UTC, abood454 commented on task_1/index.html
> +                    <img  src="assets/profile Image.png" alt="profileImages" class="img-profile" >
the width and height of the profile image need to change

2021-03-21 15:06 UTC, abood454 commented on task_1/index.html
> +                    <p class="Ps fs">Barnsley Brew Coffee</p>
the names aren't informative.

2021-03-21 15:06 UTC, abood454 commented on task_1/style.css
> +  background: #E5E5E5;
there is a white space in the top of the page , i think you should give the background to the body.

2021-03-21 15:06 UTC, abood454 commented on task_1/index.html
> +
extra space.

2021-03-21 21:13 UTC, Mohsen-Awad requested changes

2021-03-21 21:13 UTC, Mohsen-Awad commented on task_1/style.css
>    padding-bottom: 32px;
use shorthand padding

2021-03-21 21:13 UTC, Mohsen-Awad commented on task_1/style.css
>    padding-top: 3rem;
use shorthand padding

2021-03-21 21:13 UTC, Mohsen-Awad commented on task_1/style.css
> +  margin-top: 20px;
use shorthand margin

2021-03-21 21:13 UTC, Mohsen-Awad commented on task_1/style.css
> +  margin-left: 45px;
also use shorthand margin

2021-03-21 21:56 UTC, Mohsen-Awad approved these changes

2021-03-21 23:19 UTC, araraltawarah98 commented on task_1/fonts/google-sans-cufonfonts-webfont/style.css
> +    }
add end of file line

2021-03-21 23:25 UTC, araraltawarah98 approved these changes

2021-03-22 18:48 UTC, laithyounes commented on task_1/fonts/google-sans-cufonfonts-webfont/style.css
> +    @font-face {
this file is not formatted

2021-03-22 22:04 UTC, Mohsen-Awad approved these changes

2021-03-23 07:53 UTC, abood454 approved these changes

2021-03-23 07:58 UTC, araraltawarah98 approved these changes

2021-03-24 12:01 UTC, mmasaid commented on task_1/index.js
> +
```suggestion
```

2021-03-24 12:03 UTC, mmasaid commented on task_1/index.js
> +    const NumberOfItem = document.getElementsByClassName('Nav-items').length;
```suggestion
    const navItems = document.getElementsByClassName('Nav-items').length;
```

2021-03-24 12:05 UTC, mmasaid commented on task_1/style.css
> +.navItems{
for the class, ids, image names use kabab case and be consistent 
**please update the names for class and ids** 
```suggestion
.navItems{
```

2021-03-24 12:08 UTC, mmasaid requested changes
LGTM just need to be consistent with names conventions 
let's use Kabab case for the classes and ids and the image names

2021-03-24 14:16 UTC, mmasaid approved these changes
LGTM

2021-03-24 14:22 UTC, merged