Task 1 part 3 responsive design
ashrafabuodeh/assignments pull request #4
Opened 2021-03-29 07:05 UTC by ashrafabuodeh

2021-03-29 10:07 UTC, araraltawarah98 approved these changes

2021-03-29 10:23 UTC, araraltawarah98 requested changes

2021-03-29 10:23 UTC, araraltawarah98 commented on task_1/index.html
> +                <img src="assets/mocha-late-9.png" alt="MOCHA LATE">
don't set numbers with the name of the image.

2021-03-30 06:50 UTC, araraltawarah98 approved these changes

2021-03-30 06:52 UTC, abood454 approved these changes

2021-03-30 06:53 UTC, Mohsen-Awad approved these changes

2021-03-30 10:07 UTC, mmasaid commented on task_1/index.html
> +
```suggestion
```

2021-03-30 10:07 UTC, mmasaid commented on task_1/index.html
>      <link rel="stylesheet" href="./style.css">
No need to use bootstrap
```suggestion
```

2021-03-30 10:08 UTC, mmasaid commented on task_1/index.html
> +                    class="coffee-bens-size margin-right-with-Burger-menu">
```suggestion
                    class="coffee-bens-size burger-menu-icon">
```

2021-03-30 10:09 UTC, mmasaid commented on task_1/index.html
> +            <img src="./assets/menu.png" alt="icon menue" class="icon-menu" onclick="clickOnBurgerIcon('toggle')"
```suggestion
            <img src="./assets/menu.png" alt="icon menue" class="icon-menu" onclick="handleBurgerIconClick('toggle')"
```

2021-03-30 10:11 UTC, mmasaid commented on task_1/index.html
> +                <img src="assets/profile-image.png" alt="profileImages" class="img-profile">
Be consistent with the alt attribute

2021-03-30 10:15 UTC, mmasaid commented on task_1/index.js
>          }
Use forEach instead see this example 
```suggestion
      numberOfItem.forEach((el) => {
.....})
```

2021-03-30 10:16 UTC, mmasaid commented on task_1/index.js
> +const clickOnBurgerIcon = (elementId) => {
```suggestion
const handleBurgerIconClick = (elementId) => {
```

2021-03-30 10:18 UTC, mmasaid commented on task_1/style.css
> +}
Alphabetize Please  
```suggestion
.icon-menu {
  display: none;
  margin-left: 10px;
  width: 35px;
}
```

2021-03-30 10:19 UTC, mmasaid commented on task_1/style.css
> +}
No need for the default style
```suggestion
```

2021-03-30 10:22 UTC, mmasaid requested changes
FR: Please update the style for user profile and the burger icon 
CR: Need to address some comments

2021-03-30 13:47 UTC, mmasaid approved these changes

2021-03-31 08:11 UTC, merged